version: "3"
services:
  api:
    build: .
    restart: always
    environment:
      - PYCONKR_ADMIN_PASSWORD=${PYCONKR_ADMIN_PASSWORD:-pyconkr}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-pyconkr.settings}
      - PYCONKR_POSTGRES_NAME=${PYCONKR_POSTGRES_NAME}
      - PYCONKR_POSTGRES_HOST=${PYCONKR_POSTGRES_HOST}
      - PYCONKR_POSTGRES_PORT=${PYCONKR_POSTGRES_PORT}
      - PYCONKR_POSTGRES_USER=${PYCONKR_POSTGRES_USER}
      - PYCONKR_POSTGRES_PASSWORD=${PYCONKR_POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    volumes:
      - .:/web
      - ${LOG_VOLUME:-./log}:/log
    ports:
      - ${PORT:-8000}:8000
